### ISSUE TITLE
Cannot run: Failed to decrypt _secure_id

### ISSUE THREAD

**Issue by gavinlaking** [jrmhaig/RTanqueArena#1]
Hi Joe,

I thought I'd have a go at running this app but after `bundle install` / `yarn install`, when I start the Rails app, I'm getting the following error, and am wondering if it's something I've forgot to do or a genuine problem:

```/home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:34:in `block in execute': Failed to decrypt _secure_id (with an encrypted value of 'wCU7ojf9VjJsqOotCS7pis2IueCZrML67QeFukndBaxDYS8JnpXBIJKt8I+mIIMJ5gpPjvBTNg9Y6t1Ji4JPyxcaiaXuWwOpQ4G76GW5HsSkowOhOf9RO0DQtPLFaFZI6sYo3tVZNkw8zrCmcAXL9XnF7hrjlLhX9FyUU7i8oTMq70UurpDWIXT59VtvNG8R3tOTrSwnAOms0i/GsI3Ajy53xK9zTql1ZqKVUFlRWmvWbRtlrQ6KXxXLY5p2XcdyMJzZnAANojBReO63PW0AUeZEUYdrjHEPTPv+M/upNmPzmc0cEBuGLROK/2n9s/AD63C8ktb2c2QHxZQT1tOVWA==') in your settings. (Chamber::Errors::DecryptionFailure)
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:27:in `each_pair'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:27:in `execute'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:29:in `block in execute'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:27:in `each_pair'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:27:in `execute'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:29:in `block in execute'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:27:in `each_pair'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:27:in `execute'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/filters/failed_decryption_filter.rb:11:in `execute'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/settings.rb:274:in `block in data'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/settings.rb:273:in `each'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/settings.rb:273:in `inject'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/settings.rb:273:in `data'
	from /home/development/.gem/ruby/2.4.0/gems/chamber-2.11.0/lib/chamber/settings.rb:246:in `method_missing'
	from /home/development/Source/RTanqueArena/config/initializers/omniauth.rb:2:in `block in <top (required)>'```

I've clipped the rest of the stacktrace as I think that's mostly Rails stuff and not important.

Thanks very much for your time,

Gav

**Comment by jrmhaig** [comment]
Hi Gav.

I've only just seen this issue so I'm sorry for taking so long to reply.

As far as I can tell the error is because you cannot decrypt the encrypted id and secret for Github OAuth without the key in my (private) `.chamber.pem` file. An explanation of how encrypted settings work in Chamber can be found [here](https://github.com/thekompanee/chamber/wiki/Basic-Usage) and details of the Github OAuth gem are [here](https://github.com/omniauth/omniauth-github).

Having said that, there isn't really much in this repository yet but I'm hoping to get [RTanque](https://github.com/awilliams/RTanque) working in a web page. There is still a long way to go.

Thanks for dropping by.

**Comment by jrmhaig** [comment]
Alternatively, just change `_secure_id` and `_secure_secret` in `config/settings.yml` to `id` and `secret`. OAuth will not work but I think that the site will work otherwise.

I probably shouldn't have the `_secure` versions in the development section of the configuration anyway but I'm just playing around at the moment and I didn't expect anyone else to see it.
